backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artworks"
    label: "Artworks"
    folder: "content/artworks"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "about"
    label: "About"
    files:
      - file: "content/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "seo"
    label: "SEO"
    files:
      - file: "content/seo.md"
        label: "SEO"
        name: "seo"
        fields:
          - { label: "Meta Title", name: "meta_title", widget: "string" }
          - { label: "Meta Description", name: "meta_description", widget: "text" }
